### ISSUE TITLE
Убрать референс с Mock на Blazor

### ISSUE THREAD

**Issue by FrediKats** [kysect/Recademy#19]
Сейчас генератор ссылается на весь проект, а там быть не должно. Все сущности почти вынесли в .Library, нужно убедится, что их достаточно, удалить зависимость от .Blazor и ссылаться а .Library.
(спойлер: там сейчас нет DbCotnext)

**Comment by FrediKats** [comment]
Обсудили с @hrrrrustic, есть подводные камни. Пока не трогаем.

**Comment by hrrrrustic** [comment]
Ого, круто, а где я был во время этого обсуждения?

**Comment by FrediKats** [comment]
Это было 3 месяца назад, я просто забыл закрыть.
