### ISSUE TITLE
Возврат циклических данных

### ISSUE THREAD

**Issue by hrrrrustic** [kysect/Recademy#20]
https://github.com/TEF-Dev/Recademy/blob/master/Recademy/Services/ReviewService.cs#L28

Скорее всего такая проблема во всех инклюдах. Как минимум выше пример. В ревью реквест инклюдим юзера, у которого в полях опять ревью реквесты -> получаем цикл. Блейзор это как-то переварил, но сериализатор в джсон такое не оценит. Нужно наверно инклюдить что-то конкретное у юзера, либо что-то придумывать, это не проблема сериализатора, тут действительно что-то не так с логикой.

**Comment by FrediKats** [comment]
Почему *invalid*?

Ну и да, в итоге это перепишется на контроллеры? Контролеры должны возвращать Dto, никаких моделей. И соответственно нужно реализовать конвертор в дто, где не будет циклов.

**Comment by hrrrrustic** [comment]
Тут явно надо не конвертить, а просто возвращать _то, что действительно нужно_

**Comment by hrrrrustic** [comment]
Кстати про возврат моделей тоже такое, если обмазаться шлюзами, то апи станет внутренним и закрытым и почему бы не возвращать что угодно)))

**Comment by FrediKats** [comment]
Дак дело не в открытых/закрытых.  Модели проектируются с учетом нормализации данных. В отрыве от бд - с ними сложно работать, они очень не удобны. К тому же, то что у тебя будет шлюз не отменяет того факта, что данные возвращать то энивей нужно.

**Comment by FrediKats** [comment]
Отрефакторил логику ревью - мы возвращали чистые модели с базы + при этом юзали инклюды. Скорее всего, это и убивало сериализацию. Переписал все возвращаемые типы - там теперь только dto.

Чекнуть изменения можно в 4b226ac43ce8b801c4ef3bd56f3338e28ab1a6ca
