### ISSUE TITLE
Удалить токен и прочую сенсетив инормацию

### ISSUE THREAD

**Issue by FrediKats** [kysect/Recademy#6]
В проекте вшиты токены, id и еще какая-то сенсетив информация. Ее так хранить не нужно. Если она реально нужна для работы - нужно посмотреть в сторону User secrets (фича VS кажется) или поресерчить бест-практис хранения подобной информации.

**Comment by riiji** [comment]
https://github.com/TEF-Dev/Recademy/pull/17

**Comment by FrediKats** [comment]
Как и было предложено в прилинкованой ишуе - нужно бы сделать таблицу в которой бы все лежало. Советую сделать ее как пару ключ-значение, для каждой опции будет свой GUID, по нему будет браться из базы что-то.:

```C#
public static Guid TokemKey = Guid.Parse("....");

public string GetToken()
{
    return _db.Settings.Find(TokenKey);
}
````
