### ISSUE TITLE
Авторизация пользователя

### ISSUE THREAD

**Issue by FrediKats** [kysect/Recademy#7]
Убрать id пользователя, которое захардкорили в системе и реализовать нормальную авторизацию.

**Comment by hrrrrustic** [comment]
Так это же ты его захардкодил!

**Comment by annchous** [comment]
@FrediKats а покажешь, о чём речь?

**Comment by hrrrrustic** [comment]
Господи, ты зачем это ковыряешь...

**Comment by hrrrrustic** [comment]
Скорее всего уже неактуально, это было на блазор фронте

**Comment by annchous** [comment]
> Скорее всего уже неактуально, это было на блазор фронте

А, ну супер, я тогда закрою.
